/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogBlogSlugRouteImport } from './routes/blog/$blogSlug'
import { Route as DestinationsDestSlugRouteImport } from './routes/destinations/$destSlug'
import { Route as ExperiencesIndexRouteImport } from './routes/experiences/index'
import { Route as ExperiencesLakesHillsRouteImport } from './routes/experiences/lakes-hills'
import { Route as ExperiencesSnowSkiingRouteImport } from './routes/experiences/snow-skiing'
import { Route as ExperiencesTemplesFaithRouteImport } from './routes/experiences/temples-faith'
import { Route as ExperiencesTrekkingRouteImport } from './routes/experiences/trekking'
import { Route as ExperiencesVillageLifeRouteImport } from './routes/experiences/village-life'
import { Route as ExperiencesWildlifeRouteImport } from './routes/experiences/wildlife'
import { Route as ExperiencesYogaWellnessRouteImport } from './routes/experiences/yoga-wellness'
import { Route as PackagesPackageSlugRouteImport } from './routes/packages/$packageSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogBlogSlugRoute = BlogBlogSlugRouteImport.update({
  id: '/$blogSlug',
  path: '/$blogSlug',
  getParentRoute: () => BlogRoute,
} as any)
const DestinationsDestSlugRoute = DestinationsDestSlugRouteImport.update({
  id: '/$destSlug',
  path: '/$destSlug',
  getParentRoute: () => DestinationsRoute,
} as any)
const ExperiencesIndexRoute = ExperiencesIndexRouteImport.update({
  id: '/experiences/',
  path: '/experiences/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesLakesHillsRoute = ExperiencesLakesHillsRouteImport.update({
  id: '/experiences/lakes-hills',
  path: '/experiences/lakes-hills',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesSnowSkiingRoute = ExperiencesSnowSkiingRouteImport.update({
  id: '/experiences/snow-skiing',
  path: '/experiences/snow-skiing',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesTemplesFaithRoute = ExperiencesTemplesFaithRouteImport.update({
  id: '/experiences/temples-faith',
  path: '/experiences/temples-faith',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesTrekkingRoute = ExperiencesTrekkingRouteImport.update({
  id: '/experiences/trekking',
  path: '/experiences/trekking',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesVillageLifeRoute = ExperiencesVillageLifeRouteImport.update({
  id: '/experiences/village-life',
  path: '/experiences/village-life',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesWildlifeRoute = ExperiencesWildlifeRouteImport.update({
  id: '/experiences/wildlife',
  path: '/experiences/wildlife',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesYogaWellnessRoute = ExperiencesYogaWellnessRouteImport.update({
  id: '/experiences/yoga-wellness',
  path: '/experiences/yoga-wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesPackageSlugRoute = PackagesPackageSlugRouteImport.update({
  id: '/$packageSlug',
  path: '/$packageSlug',
  getParentRoute: () => PackagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/packages': typeof PackagesRouteWithChildren
  '/blog/$blogSlug': typeof BlogBlogSlugRoute
  '/destinations/$destSlug': typeof DestinationsDestSlugRoute
  '/experiences/lakes-hills': typeof ExperiencesLakesHillsRoute
  '/experiences/snow-skiing': typeof ExperiencesSnowSkiingRoute
  '/experiences/temples-faith': typeof ExperiencesTemplesFaithRoute
  '/experiences/trekking': typeof ExperiencesTrekkingRoute
  '/experiences/village-life': typeof ExperiencesVillageLifeRoute
  '/experiences/wildlife': typeof ExperiencesWildlifeRoute
  '/experiences/yoga-wellness': typeof ExperiencesYogaWellnessRoute
  '/packages/$packageSlug': typeof PackagesPackageSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/experiences/': typeof ExperiencesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/packages': typeof PackagesRouteWithChildren
  '/blog/$blogSlug': typeof BlogBlogSlugRoute
  '/destinations/$destSlug': typeof DestinationsDestSlugRoute
  '/experiences/lakes-hills': typeof ExperiencesLakesHillsRoute
  '/experiences/snow-skiing': typeof ExperiencesSnowSkiingRoute
  '/experiences/temples-faith': typeof ExperiencesTemplesFaithRoute
  '/experiences/trekking': typeof ExperiencesTrekkingRoute
  '/experiences/village-life': typeof ExperiencesVillageLifeRoute
  '/experiences/wildlife': typeof ExperiencesWildlifeRoute
  '/experiences/yoga-wellness': typeof ExperiencesYogaWellnessRoute
  '/packages/$packageSlug': typeof PackagesPackageSlugRoute
  '/blog': typeof BlogIndexRoute
  '/experiences': typeof ExperiencesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/packages': typeof PackagesRouteWithChildren
  '/blog/$blogSlug': typeof BlogBlogSlugRoute
  '/destinations/$destSlug': typeof DestinationsDestSlugRoute
  '/experiences/lakes-hills': typeof ExperiencesLakesHillsRoute
  '/experiences/snow-skiing': typeof ExperiencesSnowSkiingRoute
  '/experiences/temples-faith': typeof ExperiencesTemplesFaithRoute
  '/experiences/trekking': typeof ExperiencesTrekkingRoute
  '/experiences/village-life': typeof ExperiencesVillageLifeRoute
  '/experiences/wildlife': typeof ExperiencesWildlifeRoute
  '/experiences/yoga-wellness': typeof ExperiencesYogaWellnessRoute
  '/packages/$packageSlug': typeof PackagesPackageSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/experiences/': typeof ExperiencesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/packages'
    | '/blog/$blogSlug'
    | '/destinations/$destSlug'
    | '/experiences/lakes-hills'
    | '/experiences/snow-skiing'
    | '/experiences/temples-faith'
    | '/experiences/trekking'
    | '/experiences/village-life'
    | '/experiences/wildlife'
    | '/experiences/yoga-wellness'
    | '/packages/$packageSlug'
    | '/blog/'
    | '/experiences/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/destinations'
    | '/packages'
    | '/blog/$blogSlug'
    | '/destinations/$destSlug'
    | '/experiences/lakes-hills'
    | '/experiences/snow-skiing'
    | '/experiences/temples-faith'
    | '/experiences/trekking'
    | '/experiences/village-life'
    | '/experiences/wildlife'
    | '/experiences/yoga-wellness'
    | '/packages/$packageSlug'
    | '/blog'
    | '/experiences'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/packages'
    | '/blog/$blogSlug'
    | '/destinations/$destSlug'
    | '/experiences/lakes-hills'
    | '/experiences/snow-skiing'
    | '/experiences/temples-faith'
    | '/experiences/trekking'
    | '/experiences/village-life'
    | '/experiences/wildlife'
    | '/experiences/yoga-wellness'
    | '/packages/$packageSlug'
    | '/blog/'
    | '/experiences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  PackagesRoute: typeof PackagesRouteWithChildren
  ExperiencesLakesHillsRoute: typeof ExperiencesLakesHillsRoute
  ExperiencesSnowSkiingRoute: typeof ExperiencesSnowSkiingRoute
  ExperiencesTemplesFaithRoute: typeof ExperiencesTemplesFaithRoute
  ExperiencesTrekkingRoute: typeof ExperiencesTrekkingRoute
  ExperiencesVillageLifeRoute: typeof ExperiencesVillageLifeRoute
  ExperiencesWildlifeRoute: typeof ExperiencesWildlifeRoute
  ExperiencesYogaWellnessRoute: typeof ExperiencesYogaWellnessRoute
  ExperiencesIndexRoute: typeof ExperiencesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$blogSlug': {
      id: '/blog/$blogSlug'
      path: '/$blogSlug'
      fullPath: '/blog/$blogSlug'
      preLoaderRoute: typeof BlogBlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/destinations/$destSlug': {
      id: '/destinations/$destSlug'
      path: '/$destSlug'
      fullPath: '/destinations/$destSlug'
      preLoaderRoute: typeof DestinationsDestSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/experiences/': {
      id: '/experiences/'
      path: '/experiences'
      fullPath: '/experiences/'
      preLoaderRoute: typeof ExperiencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/lakes-hills': {
      id: '/experiences/lakes-hills'
      path: '/experiences/lakes-hills'
      fullPath: '/experiences/lakes-hills'
      preLoaderRoute: typeof ExperiencesLakesHillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/snow-skiing': {
      id: '/experiences/snow-skiing'
      path: '/experiences/snow-skiing'
      fullPath: '/experiences/snow-skiing'
      preLoaderRoute: typeof ExperiencesSnowSkiingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/temples-faith': {
      id: '/experiences/temples-faith'
      path: '/experiences/temples-faith'
      fullPath: '/experiences/temples-faith'
      preLoaderRoute: typeof ExperiencesTemplesFaithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/trekking': {
      id: '/experiences/trekking'
      path: '/experiences/trekking'
      fullPath: '/experiences/trekking'
      preLoaderRoute: typeof ExperiencesTrekkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/village-life': {
      id: '/experiences/village-life'
      path: '/experiences/village-life'
      fullPath: '/experiences/village-life'
      preLoaderRoute: typeof ExperiencesVillageLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/wildlife': {
      id: '/experiences/wildlife'
      path: '/experiences/wildlife'
      fullPath: '/experiences/wildlife'
      preLoaderRoute: typeof ExperiencesWildlifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/yoga-wellness': {
      id: '/experiences/yoga-wellness'
      path: '/experiences/yoga-wellness'
      fullPath: '/experiences/yoga-wellness'
      preLoaderRoute: typeof ExperiencesYogaWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$packageSlug': {
      id: '/packages/$packageSlug'
      path: '/$packageSlug'
      fullPath: '/packages/$packageSlug'
      preLoaderRoute: typeof PackagesPackageSlugRouteImport
      parentRoute: typeof PackagesRoute
    }
  }
}

interface BlogRouteChildren {
  BlogBlogSlugRoute: typeof BlogBlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogBlogSlugRoute: BlogBlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DestinationsRouteChildren {
  DestinationsDestSlugRoute: typeof DestinationsDestSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsDestSlugRoute: DestinationsDestSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface PackagesRouteChildren {
  PackagesPackageSlugRoute: typeof PackagesPackageSlugRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesPackageSlugRoute: PackagesPackageSlugRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  PackagesRoute: PackagesRouteWithChildren,
  ExperiencesLakesHillsRoute: ExperiencesLakesHillsRoute,
  ExperiencesSnowSkiingRoute: ExperiencesSnowSkiingRoute,
  ExperiencesTemplesFaithRoute: ExperiencesTemplesFaithRoute,
  ExperiencesTrekkingRoute: ExperiencesTrekkingRoute,
  ExperiencesVillageLifeRoute: ExperiencesVillageLifeRoute,
  ExperiencesWildlifeRoute: ExperiencesWildlifeRoute,
  ExperiencesYogaWellnessRoute: ExperiencesYogaWellnessRoute,
  ExperiencesIndexRoute: ExperiencesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
